package com.revature.post_fruits;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "fruits")
public class Fruit {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String color;

    @DynamoDBAttribute
    private double cost;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private double weight;

    @DynamoDBAttribute
    private int juiceLevel;
}
